### PR TITLE
added burning, and showed 'hidden' (?) dealer card

### PR DESCRIPTION
**Pull request by RoseApollo**

### CODE REVIEW

**Comment by ElijahMMiller** [comment]
trash game, developers are noobs. Pls make roblox on C# to play on lessons because school blocked roblox in school interenet!!11!!1!! !

**Comment by ElijahMMiller** [comment]
ezezezez

**Comment by RoseApollo** [comment]
im gonna report you

**Comment by ElijahMMiller** [comment]
pls no my dad is ceo of github and will delete yuor accoun

**Comment by RoseApollo** [comment]
im besties with linus, he will delete git

**Comment by ElijahMMiller** [comment]
Linus is dead. Linus remains dead. And we have killed him. How shall we comfort ourselves, the murderers of all murderers? What was holiest and mightiest of all that the world has yet owned has bled to death under our knives: who will wipe this blood off us? What water is there for us to clean ourselves? What festivals of atonement, what sacred games shall we have to invent? Is not the greatness of this deed too great for us? Must we ourselves not become Linus' simply to appear worthy of it?

**Comment by RoseApollo** [comment]
<333

**Pull request merged**
